version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      postgresql:
        patterns:
          - "*postgresql*"
      maven:
        patterns:
          - "*maven*"
      kotlin:
        patterns:
          - "*kotlin*"

  - package-ecosystem: "npm"
    directory: "/mancalaje-fe"
    schedule:
      interval: "daily"
    groups:
      react:
        patterns:
          - "@react*"
          - "react*"
          - "@types/react*"

  - package-ecosystem: "npm"
    directory: "/kala-game-web"
    schedule:
      interval: "daily"
    groups:
      angular:
        patterns:
          - "@angular*"
          - "angular*"
