jobs:
  include:
    - language: node_js
      stage: Frontend Test (Angular Releases)
      node_js: 12
      script:
        - yarn config set workspaces-experimental true
        - npm install -g nodeunit jscoverage coveralls jest codecov
        - yarn install
        - jest --coverage --projects packages/kala-game-web
        - coveralls < packages/kala-game-web/coverage/lcov.info
        - cd packages/kala-game-web
        - codecov

    - language: node_js
      stage: Frontend Test (React Releases)
      node_js: 12
      script:
        - yarn config set workspaces-experimental true
        - npm install -g nodeunit jscoverage coveralls jest codecov
        - yarn install
        - jest --coverage --projects packages/mancalaje-fe
        - coveralls < packages/mancalaje-fe/coverage/lcov.info
        - cd packages/mancalaje-fe
        - codecov

    - language: java
      stage: Backend Test (All Java 11 Services)
      jdk:
        - openjdk11
      install: mvn dependency:resolve
      script:
        - mvn clean install coveralls:report -Dconsolerizer.show=false -DrepoToken=${COVERALLS_TOKEN}
        - bash <(curl -s https://codecov.io/bash)

