jobs:
  include:
    - language: node_js
      stage: Frontend Test (React + Angular Releases)
      node_js: 12
      script:
        - yarn config set workspaces-experimental true
        - npm install -g nodeunit jscoverage coveralls jest codecov
        - apt-get install lcov
        - mkdir coverage
        - yarn install
        - yarn workspaces run coverage
        - find packages -name lcov.info -exec echo -a {} \; | xargs lcov -o coverage/lcov.info
        - coveralls < coverage/lcov.info && codecov

    - language: java
      stage: Backend Test (All Java 11 Services)
      jdk:
        - openjdk11
      install: mvn dependency:resolve
      script:
        - mvn clean install coveralls:report -Dconsolerizer.show=false -DrepoToken=${COVERALLS_TOKEN}
        - bash <(curl -s https://codecov.io/bash)

