jobs:
  include:
    - language: node_js
      node_js: 12
      script:
        - cd mancalaje-fe
        - npm install -g nodeunit jscoverage coveralls jest
        - yarn install
        - jest --coverage && coveralls < coverage/lcov.info
        - cd ..

    - language: java
      jdk:
        - openjdk11
      install: mvn dependency:resolve
      script:
        - mvn clean install coveralls:report -Dconsolerizer.show=false -DrepoToken=${COVERALLS_TOKEN}
        - bash <(curl -s https://codecov.io/bash)

