version: "3.7"
services:
  mancalaje:
    hostname: mancalaje
    build:
      context: .
    ports:
      - "8080:80"

  mancalaje-postgres:
    hostname: mancalaje-postgres
    image: library/postgres:12
    env_file:
      - docker-psql/.env
