version: "3.7"
services:
  mancala:
    hostname: mancala
    build:
      context: .
    ports:
      - "8080:80"

  postgres:
    hostname: postgres
    image: library/postgres:12
    env_file:
      - docker-psql/.env
