kind: Service
apiVersion: v1
metadata:
  name: mancalaje
spec:
  selector:
    app: mancalaje
    tier: backend
  ports:
    - protocol: TCP
      port: 8087
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mancalaje
spec:
  selector:
    matchLabels:
      app: mancalaje
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mancalaje
        tier: backend
    spec:
      containers:
        - name: mancalaje
          image: mancalaje:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
