kind: Service
apiVersion: v1
metadata:
  name: mancalaje-service
spec:
  selector:
    app: mancalaje-service
    tier: backend
  ports:
    - protocol: TCP
      port: 8087
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mancalaje-service
spec:
  selector:
    matchLabels:
      app: mancalaje-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mancalaje-service
        tier: backend
    spec:
      containers:
        - name: mancalaje-service
          image: mancalaje-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
