kind: Service
apiVersion: v1
metadata:
  name: mancalaje-fe
spec:
  type: NodePort
  selector:
    app: mancalaje-fe
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mancalaje-fe
spec:
  selector:
    matchLabels:
      app: mancalaje-fe
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: mancalaje-fe
        tier: frontend
        track: stable
    spec:
      containers:
        - name: mancalaje-fe
          image: mancalaje-fe:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80