version: 2
jobs:
  build-service:
    machine:
      image: ubuntu-2204:2023.04.2
    resource_class: large
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Install SDK 20
          command: wget https://download.java.net/java/GA/jdk20.0.1/b4887098932d415489976708ad6d1a4b/9/GPL/openjdk-20.0.1_linux-x64_bin.tar.gz &&
            tar xvf openjdk-20.0.1_linux-x64_bin.tar.gz &&
            sudo mv jdk-20*/ /opt/jdk20 &&
            export JAVA_HOME=/opt/jdk20 &&
            export PATH=$PATH:$JAVA_HOME/bin

      - run:
          name: Build
          command: export JAVA_HOME=/opt/jdk20 &&
              export PATH=$PATH:$JAVA_HOME/bin &&
              mvn -B -DskipTests clean package

      - run:
          name: Test
          command: export JAVA_HOME=/opt/jdk20 &&
              export PATH=$PATH:$JAVA_HOME/bin &&
              mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}


  build-front-end:
    docker:
        - image: cimg/node:22.0.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
         name: Set Experimental Workspaces
         command: yarn config set workspaces-experimental true
      - run:
         name: Front End build (Angular + React releases)
         command: yarn install

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-service
      - build-front-end
