server:
  port: 8087
  servlet:
    context-path: /api

logging:
  level:
    root: INFO

mancalaje:
  max-rooms: 50
  max-users: 100
  mail:
    no-reply: mancalaje.no.reply@joaofilipesabinoesperancinha.nl

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
  mail:
    host: localhost
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeou: 5000
