server:
  port: 8087

logging:
  level:
    root: INFO

mancalaje:
  max-rooms: 50
  max-users: 100

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow