kind: Service
apiVersion: v1
metadata:
  name: mancalaje-postgresql
spec:
  selector:
    app: mancalaje-postgresql
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mancalaje-postgresql
spec:
  selector:
    matchLabels:
      app: mancalaje-postgresql
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: mancalaje-postgresql
        tier: backend
    spec:
      containers:
        - name: mancalaje-postgresql
          image: mancalaje-postgresql:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
