name: mancalaje-pull_request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 20
          uses: actions/setup-java@v3
          with:
            java-version: '20'
            distribution: 'adopt'
        - uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: Install Jest Kala Game Web
          run: cd kala-game-web && yarn && yarn add jest --dev

        - name: Install Jest Mancala Je Fe
          run: cd mancalaje-fe && yarn && yarn add jest --dev

        - name: Build and Test
          run:  mvn clean install jacoco:prepare-agent package jacoco:report

        - name: Install SNYK
          run: npm install -g snyk

        - name: Node Coverage Kala Game Web
          run: cd kala-game-web && npm run coverage

        - name: Node Coverage Mancala Je Fe
          run: cd mancalaje-fe && npm run coverage

        - name: Version statuses
          run: make version-status
